//
//  CardStatus.swift
//  GNS Secure Login
//
//  Created by Peter Bassem on 26/07/2021.
//

import Foundation

enum CardStatus {
    case BLUETOOTH_SUPPORT, DEVICE_BLUETOOTH_SUPPORT, BLUETOOTH_TERMINAL_MANAGER,
    BLUETOOTH_TERMINAL_FACTORY, START_SCAN, STOP_SCAN, LIST, DISCONNECT, CARD_STATE, GET_CARD_STATE
}
